apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpu-throttle-monitor
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader-binding
subjects:
- kind: ServiceAccount
  name: cpu-throttle-monitor
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cpu-throttle-config
  namespace: default
data:
  NAMESPACE: "boutique"
  CONTAINER_NAME: "server"
  LABEL_SELECTOR: "app=cartservice"
  WAIT_SECONDS: "0"
  COMPLETE_CGROUP_PATH: "/sys/fs/cgroup/cpu/cpu.stat"
---
apiVersion: v1
kind: Pod
metadata:
  name: cpu-throttle-monitor
  namespace: default
spec:
  serviceAccountName: cpu-throttle-monitor
  containers:
  - name: monitor
    image: sagarnewdocker/cpu:latest
    imagePullPolicy: Always
    args: ["--verbose", "--json"]
    envFrom:
    - configMapRef:
        name: cpu-throttle-config
    volumeMounts:
    - name: cgroup
      mountPath: /sys/fs/cgroup
      readOnly: true
  volumes:
  - name: cgroup
    hostPath:
      path: /sys/fs/cgroup
